apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: team-catalog-backend-alerts
  namespace: nom
  labels:
    team: nom
spec:
  groups:
    - name: team-catalog-backend_down
      rules:
        - alert: team-catalog-backend applikasjon nede
          expr: up{app="team-catalog-backend", job="kubernetes-pods"} == 0
          for: 3m
          annotations:
            action: "`kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }} -c {{ $labels.app }}` for logger"
            summary: "{{ $labels.app }} er nede"
          labels:
            namespace: nom
            severity: critical
    - name: team-catalog-backend_high_failrate
      rules:
        - alert: team-catalog-backend høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="team-catalog-backend",log_team="nom",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="team-catalog-backend",log_team="nom"}[3m]))) > 10
          for: 3m
          annotations:
            action: "Sjekk loggene til app {{ $labels.log_app }}, for å se hvorfor det er så mye feil"
          labels:
            namespace: nom
            severity: warning