name: Deploy Team-Catalog Backend alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/nais/alerts-backend-dev-fss.yaml'
      - 'apps/backend/nais/alerts-backend-prod-fss.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/backend/nais/alerts-backend-dev-fss.yaml

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/backend/nais/alerts-backend-prod-fss.yaml
