name: Deploy Team-Catalog Frackend alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - 'apps/frackend/nais/alerts-frackend-dev-gcp.yaml'
      - 'apps/frackend/nais/alerts-frackend-prod-gcp.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/frackend/nais/alerts-frackend-dev-gcp.yaml

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/frackend/nais/alerts-frackend-prod-gcp.yaml
