name: 'deploy: backend'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/deploy-backend.yaml'
      - 'apps/backend/**'
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/teambackend:${{ github.sha }}

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn compile --batch-mode
      - name: Test and Package
        run: mvn package --batch-mode

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker container
        uses: docker/build-push-action@v3
        with:
          context: apps/backend
          push: true
          tags: ${{ env.IMAGE }}
          build-args: JAR_PATH=target/app.jar

#  deploy-preprod:
#    name: Backend - deploy Dev FSS
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-fss
#          RESOURCE: apps/backend/nais/backend-fss.yaml
#          VARS: apps/backend/nais/backend-dev-fss-vars.yaml
          
#  deploy-prod:
#    name: Backend - deploy Prod FSS
#    needs: build
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-fss
#          RESOURCE: apps/backend/nais/backend-fss.yaml
#          VARS: apps/backend/nais/backend-prod-fss-vars.yaml

  deploy-prod-gcp:
    name: Backend - deploy Prod FSS
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_ORG_DEPLOY_APIKEY  }}
          CLUSTER: prod-gcp
          RESOURCE: apps/backend/nais/backend-prod-gcp.yaml